steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west2-docker.pkg.dev/$PROJECT_ID/aliss-mcp-v2/aliss-mcp-v2:$COMMIT_SHA',
        '.'
      ]

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/aliss-mcp-v2/aliss-mcp-v2:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
